### ISSUE TITLE
RFE: Verify org-policies

### ISSUE THREAD

**Issue by nsabine** [GoogleCloudPlatform/client-side-encryption#8]
Verify the following constraints are applied:

Disable Serial Port Logging
- `constraints/compute.disableSerialPortLogging`
- `enforced: true`

Require Confidential VM
- `constraints/compute.requireConfidentialVm`
- `enforced: true`

Require Shielded VM
- `constraints/compute.requireShieldedVm`
- `enforced: true`

Restrict Non-Confidential Computing
- `constraints/compute.restrictNonConfidentialComputing`
-     "listPolicy": {
        "deniedValues": [
          "compute.googleapis.com"
        ]
      }

Disable Cloud Logging
- `constraints/gcp.disableCloudLogging`
- `enforced: true`

Resource Locations
- `constraints/gcp.resourceLocations`
-     "listPolicy": {
        "allowedValues": [
          "in:us-locations"
        ]
      }

**Comment by jason-callaway** [comment]
Will Not Fix. After review we realized that users will probably lack the IAM privilege necessary to talk to the Cloud Resource Manager endpoint.
